### ISSUE TITLE
Fun Dec Hover Types are incorrect

### ISSUE THREAD

**Issue by T-Brick** [azdavis/millet#21]
## Expected behavior

The hovering over the function being declared in a fun declaration returns the wrong type. As seen in the picture, Millet's hovering of the type seems to be an uncurried version of the inputs, rather than the type of the function (in this case `add`)

<img width="392" alt="image" src="https://user-images.githubusercontent.com/13863187/213031106-f8626188-1a40-404b-ba5e-f35367c75e91.png">

## Actual behavior

Above I should expect to see `ORD_SET.set -> (string * int) -> ORD_SET.set`

**Comment by azdavis** [comment]
fixed in 60e3ea3f76df55c2cf7d8a4cd552bb3cadf706ec
