### ISSUE TITLE
Crash on deleting ≤, ≥, or ≠

### ISSUE THREAD

**Issue by ashermkn1** [azdavis/millet#22]
## Environment

- Millet version: v0.7.4
- Editor version: VSCode
- OS version: MacOS Monterey 12.6.2

## Steps to reproduce

Simply type any character with more than one Unicode value in it (such as ≥, ≤, ≠, etc.) and then delete it. Millet will crash

EDIT: This has now happened a few times without typing one of these characters, but I am still not sure why, trying to figure it out.

## Expected behavior

I'm honestly not sure. I only was using it in my function specifications (150 woot), not the actual functions.

## Actual behavior

`thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)'`

**Comment by azdavis** [comment]
Should be fixed in v0.7.5
