### ISSUE TITLE
[Feature Request] Distribute binaries to ease usage with other editors

### ISSUE THREAD

**Issue by igorlfs** [azdavis/millet#25]
## Problem

While there's a VSCode extension, usage with others editors is a bit more difficult given it's required to build the program.

## Solution

Distribute binaries to ease usage with other editors.

**Comment by azdavis** [comment]
Haven’t looked into the github docs too much but i think you can attach binaries to github releases. Maybe we could do that.

I’m not too interested in maintaining millet support for all the various myriad package managers that exist, but other people have already added millet to e.g. nix and arch, i believe.

Also in the meantime you can download the vs code extension for your platform and extract the binary from that.

**Comment by igorlfs** [comment]
Hey, thanks for quick reply!

> I’m not too interested in maintaining millet support for all the various myriad package managers that exist, but other people have already added millet to e.g. nix and arch, i believe.

Yeah, absolutely. I'm on arch, and there's an AUR package.

But I'm more interested in an integration with [Mason](https://github.com/williamboman/mason.nvim), which is kind of an "install everything for neovim" (e.g, LSP Servers, Linters). I've opened an [issue](https://github.com/williamboman/mason.nvim/issues/1097) there, requesting for Millet support, but as I understand it, the better way to solve this problem would be to not rely on building Millet, as it requires Rust, but instead extracting it from somewhere.

**Comment by azdavis** [comment]
Well I looked into some github actions to create a github release and attach files and I think i got it to work. The latest relese 0.8.3 uses the new github actions ci and it attaches the pre compiled binary as well as the packaged vsix files to the github release.

https://github.com/azdavis/millet/releases/tag/v0.8.3

**Comment by igorlfs** [comment]
Thanks!
