### ISSUE TITLE
Add inlay hints

### ISSUE THREAD

**Issue by azdavis** [azdavis/millet#28]
## Problem

You can hover over things to get their type, but there's no way for Millet to "always" show this information without hovering.

## Solution

Add support for inlay hints, which could show this information. It's in the LSP standard.

**Comment by azdavis** [comment]
Already somewhat implemented

https://github.com/azdavis/millet/blob/4e0bed39cdb0e858cbbf84248537bdd3a01dabcc/crates/analysis/src/lib.rs/#L280-L308

**Comment by azdavis** [comment]
Done in v0.12.0

**Comment by bzy-debug** [comment]
Is there an option to turn off the inlay hint?

Inlay hint sometimes makes the function less readable:

<img width="717" alt="Screenshot 2023-09-11 at 23 27 15" src="https://github.com/azdavis/millet/assets/71200607/d21155b1-84eb-4064-97a1-bc6954337e6e">

It breaks the indentation of function implementation

**Comment by azdavis** [comment]
you can turn them off via editor.inlayHints.enabled in vscode

**Comment by azdavis** [comment]
https://github.com/azdavis/millet/blob/main/docs/manual.md#inlay-hints
