### ISSUE TITLE
Apply Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [azdavis/millet#37]
Hi!

Profile-Guided Optimization (PGO) can help with improving the performance of the tooling for the project like other language servers (like [rust-analyzer](https://github.com/rust-lang/rust-analyzer/issues/) or [clangd](https://github.com/llvm/llvm-project/issues/63486)).

Since the project is written in Rust, you can try to use [cargo-pgo](https://github.com/Kobzol/cargo-pgo). More information about PGO applications on real-world software you can find [here](https://github.com/zamazan4ik/awesome-pgo/).

**Comment by azdavis** [comment]
My thoughts are basically the same as[ matklad's](https://github.com/rust-lang/rust-analyzer/issues/9412#issuecomment-869120381):

> the tradeoff between additional perf boost and additional burden of maintaining a more complex build process is not worth it at this stage.
