### ISSUE TITLE
support for successor ML extensions

### ISSUE THREAD

**Issue by retrac0** [azdavis/millet#45]
I want to thank to azdavis and everyone else who has contributed for this; it's been great to get back into SML with good editor support! 

Is it within project scope for Millet to support some of the extensions to SML that have been informally proposed, sometimes referred to as Successor ML?  A common set of them is already implemented in MLTon, MLKit and SML/NJ, making it fairly portable now.

http://mlton.org/SuccessorML

**Comment by azdavis** [comment]
i added support for most successor ml features: https://github.com/azdavis/millet/blob/main/docs/manual.md#languagesuccessor-ml

feel free to open more issues or send patches if you need support for the remaining ones (extended constants and line comments)
