### ISSUE TITLE
Feature request: support mutual inductive types in signatures

### ISSUE THREAD

**Issue by Vtec234** [azdavis/millet#47]
## Problem

(Please forgive my terminology, this might not actually be a "mutual inductive type" in StandardML terms.) The following code is accepted by SML/NJ but shows an error in Millet.

```sml
datatype foo1 = Foo1 of bar1 (* works *)
and bar1 = Bar1 of int

datatype bar2 = Bar2 of int (* works *)
and foo2 = Foo2 of bar2
 
signature BLAH =
sig
  datatype foo3 = Foo3 of bar3 (* undefined type: `bar3` Millet(5001) *)
  and bar3 = Bar3 of int

  datatype bar4 = Bar4 of int (* works *)
  and foo4 = Foo4 of bar4
end

```

## Expected behaviour

`datatype foo3` in the signature should be accepted by Millet.

**Comment by azdavis** [comment]
fixed in v0.13.3
