### ISSUE TITLE
0.14.5 retag issue

### ISSUE THREAD

**Issue by chenrui333** [azdavis/millet#61]
👋 seeing the checksum got changed while rebuilding 0.14.5 release, raise this issue to confirm if there was some re-tagging. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/179157

**Comment by azdavis** [comment]
i might have force pushed / re tagged 0.14.5, so to try to avoid issues with that i released a new version 0.14.6

https://github.com/azdavis/millet/commit/df79631336295f64e8d5ebfd51e086364a58ed6e

there were also some issues with releasing 0.14.5 on open vsx anyway, so this let me re-attempt and it worked this time i think.
