### ISSUE TITLE
Millet hasn't recognized glob syntax from v0.14.4 onwards

### ISSUE THREAD

**Issue by Knaoinr** [azdavis/millet#62]
## Environment

- Millet version: 0.14.6
- Editor version: VSCode 1.92.2
- OS version: macOS 12.7.4

## Steps to reproduce

Set workspace root to something like `**/code/sources.mlb`.

## Expected behavior

Millet detects all `sources.mlb` files present.

## Actual behavior

Millet does not recognize any files.

![image](https://github.com/user-attachments/assets/215c64c5-f2e0-407c-940b-02e96dd5c38b)

Downgrading Millet to v0.14.3 fixes this issue.

**Comment by azdavis** [comment]
sorry for the delay.

i investigated and found the behavior started when i switched from the [glob](https://crates.io/crates/glob) crate to the [wax](https://crates.io/crates/wax) crate to handle glob patterns like `**/code/sources.mlb` in that pattern, i would expect the `**`to match 0 or more directories.

the wax crate has some surprising behavior with `**` patterns that i documented in a test case repo here: https://github.com/azdavis/wax-trouble

and opened an issue about here: https://github.com/olson-sean-k/wax/issues/61

i also just released millet v0.14.7 which switched back to the glob crate for globbing and should fix the issue you have observed.
