### ISSUE TITLE
Bug in parsing higher-order infix operators.

### ISSUE THREAD

**Issue by MizurenNanako** [azdavis/millet#64]
## Environment

- Millet version: 0.14.7-1 (from archlinux user repository)
- Editor version: NVIM 0.10.2
- OS version: Archlinux x86_64 Linux 6.11.8-zen1-2-zen

## Steps to reproduce

Write something like:

```sml
fun println s =
  (print s; print "\n")

infix 0 |>
fun (a: 'a) |> (b: 'a -> 'b) = b a

val () = "hello" ^ " " ^ "world" |> println
```

## Expected behavior

It passed type check of both SML/NJ and MLton:

![report1](https://github.com/user-attachments/assets/95e7db37-570e-44ac-8a52-8a8fbed02730)

![report2](https://github.com/user-attachments/assets/42c14856-f5cf-4131-91cb-14b295920539)

## Actual behavior

However, Millet reported an type error. This is likely a bug on parsing.

![report3](https://github.com/user-attachments/assets/d4c14238-5199-4144-b77b-bf590dcef21c)

**Comment by azdavis** [comment]
i cannot reproduce with your code example where `|>` and the usage of `|>` are in the same file. but i can reproduce if `|>` is in a different file and i import it. i think it's likely that `|>` is in scope, but the infix-ness of `|>` is not in scope.

you can do two things:

1. put:

    ```toml
    [language]
    fixity-across-files = true
    ```

    in your millet.toml and restart millet. this will allow importing fixities but will also possibly make millet slower, since it has to do more work to correctly track all the fixity environments across files.

2. in each file you use the infix op, re-declare the fixity of it. in your example that would mean putting `infix 0 |>` (or the equivalent, shorter `infix |>`) at the top of each file you import `|>` into.

**Comment by azdavis** [comment]
improve docs in b590b18e9637be9a63897f71eaa61029bba4b880 and c78f916db270e47951198e2f4e3fad10b8dee024
