### ISSUE TITLE
Running/debugging

### ISSUE THREAD

**Issue by matozoid** [azdavis/millet#9]
Hi! Thanks for the great work :-)

The install went perfectly, but when I tried to run the sample program it seemed that running and debugging is not part of Millet, I guess? What is the suggested interaction - compile and run from the command line?

**Comment by azdavis** [comment]
Yes. Currently actually running SML code is outside the scope of Millet. Millet is only a language server - it analyzes code without running it, using the "statics" from the definition of Standard ML.

To run SML code, you'll need a full implementation of Standard ML. Some popular ones are SML/NJ and MLton.

Implementing the ability to run SML (the "dynamics") would be a massive undertaking and isn't currently planned for Millet for the foreseeable future.

Thank you very much for your interest in the project!

**Comment by HarrisonGrodin** [comment]
There is a (WIP?) debugger for SML, as well, called [mulligan](https://github.com/brandonspark/mulligan).
